artipie/front

.gitattributes
.github/workflows/ci-checks.yml
pom.xml
src/main/java/com/artipie/front/Service.java
src/main/java/com/artipie/front/internal/HealthRoute.java
src/main/java/com/artipie/front/settings/ArtipieYaml.java
src/main/java/com/artipie/front/settings/YamlStorage.java
src/main/java/com/artipie/front/settings/package-info.java
src/test/java/com/artipie/front/inernal/HealthRouteTest.java
src/test/java/com/artipie/front/settings/ArtipieYamlTest.java
src/test/java/com/artipie/front/settings/YamlStorageTest.java
src/test/java/com/artipie/front/settings/package-info.java

Part of #3 
Added 
- `ArtipieYaml` class to parse yaml settings
- `YamlStorage` class from artipie/artipie to build storage from settings
- qulice plugin settings (exclude resources)
- fixed all qulice complaints and added it to CI checks

Parse artipie yaml settings

---

src/main/java/com/artipie/front/Service.java

Closes #3 
Added service start argument to accept path to config file and implemented artipie configuration storage creation from it.

Create artipie setting storage

---

pom.xml
src/main/java/com/artipie/front/Service.java
src/main/java/com/artipie/front/api/GetRepository.java
src/main/java/com/artipie/front/misc/Yaml2Json.java
src/test/java/com/artipie/front/api/GetRepositoryTest.java
src/test/java/com/artipie/front/misc/Yaml2JsonTest.java
src/test/java/com/artipie/front/misc/package-info.java
src/test/resources/GetRepositoryTest/my-maven.json
src/test/resources/GetRepositoryTest/my-maven.yaml
src/test/resources/GetRepositoryTest/my-npm-proxy.json
src/test/resources/GetRepositoryTest/my-npm-proxy.yml
src/test/resources/Yaml2JsonTest/test.json
src/test/resources/Yaml2JsonTest/test.yaml

Part of #5 
Added endpoint to get repository settings:
- created class to transform yaml to json and test
- added class for endpoint and test

feat: get repository settings endpoint

---

src/main/java/com/artipie/front/Service.java
src/main/java/com/artipie/front/api/ApiAuthFilter.java
src/main/java/com/artipie/front/misc/RouteWrap.java
src/main/java/com/artipie/front/ui/HbPage.java
src/main/java/com/artipie/front/ui/SignInPage.java

Filter API requests by media types
Refactor template rendering page
Ticket: #1

refactor: media-types, templates

---

src/main/java/com/artipie/front/Service.java
src/main/java/com/artipie/front/auth/AccessFilter.java
src/main/java/com/artipie/front/auth/AccessPermissions.java
src/main/java/com/artipie/front/auth/UserPermissions.java
src/test/java/com/artipie/front/auth/AccessPermissionsFromYamlTest.java
src/test/java/com/artipie/front/auth/UserPermissionsFromYamlTest.java

Part of #4 
Added access permissions from yaml implementation

feat: access permissions from yaml

---

src/main/java/com/artipie/front/Service.java
src/main/java/com/artipie/front/api/GetToken.java
src/main/java/com/artipie/front/auth/ApiTokens.java
src/test/java/com/artipie/front/api/GetTokenTest.java

Part of #4 
Added endpoint to generate tokens and tests.

feat: create token endpoint

---

README.md
src/main/java/com/artipie/front/Service.java
src/main/java/com/artipie/front/api/ApiAuthFilter.java

Part of #4
Added description about endpoint to generate tokens and implementation to validate tokens.

feat: validate tokens

---

README.md
pom.xml
src/main/java/com/artipie/front/AuthFilters.java
src/main/java/com/artipie/front/Service.java
src/main/java/com/artipie/front/api/PostToken.java
src/test/java/com/artipie/front/ServiceITCase.java
src/test/java/com/artipie/front/api/PostTokenTest.java
src/test/resources/ServiceITCase/_api_permissions.yml
src/test/resources/ServiceITCase/_credentials.yaml

Part of #60 
Set up integration test for `Service` and corrected several mistakes

feat: integration test set up

---

src/main/java/com/artipie/front/Service.java
src/main/java/com/artipie/front/api/Repositories.java
src/main/java/com/artipie/front/api/Storages.java
src/main/java/com/artipie/front/api/Users.java
src/main/java/com/artipie/front/auth/AccessFilter.java
src/test/java/com/artipie/front/ServiceITCase.java
src/test/resources/ServiceITCase/_credentials.yaml
src/test/resources/ServiceITCase/maven-repo.yaml

Part of #60 
Added more tests, fixed `HEAD` endpoints to return empty string instead of null

test: extend Service IT

---

pom.xml
src/test/java/com/artipie/front/ServiceITCase.java
src/test/java/com/artipie/front/TestService.java

Part of #60 
Extracted junit extension with service for tests.

test: extract service as junit extension

---

src/main/java/com/artipie/front/api/Repositories.java
src/test/java/com/artipie/front/RepoITCase.java
src/test/resources/RepoITCase/_api_permissions.yml
src/test/resources/RepoITCase/_credentials.yaml
src/test/resources/RepoITCase/maven-repo.yaml
src/test/resources/RepoITCase/pypi-repo.yaml
src/test/resources/RepoITCase/request.json

Part of #60 
Added ITs for repositories management.

test: repositories management

---

src/main/java/com/artipie/front/api/Storages.java
src/main/java/com/artipie/front/misc/RequestPath.java
src/test/java/com/artipie/front/RepoPermITCase.java
src/test/java/com/artipie/front/StorageAliasesITCase.java
src/test/resources/StorageAliasesITCase/_api_permissions.yml
src/test/resources/StorageAliasesITCase/_credentials.yaml
src/test/resources/StorageAliasesITCase/_storages.yaml

Part of #60 
Added integration tests for storages API.

test: added ITs for storages aliases API

---

src/main/resources/html/repo

fix: `cancel` button for repository create page

---

src/main/resources/html/repo

Closes #78 
Added cancel button to repo edit page

feat: add cancel button to repo edit page

---

src/main/java/com/artipie/front/settings/ArtipieYaml.java

Closes #79 
Added support for env auth.

feat: auth from env support

---

pom.xml
src/main/java/com/artipie/front/auth/GithubCredentials.java
src/main/java/com/artipie/front/settings/ArtipieYaml.java
src/test/java/com/artipie/front/auth/GithubCredentialsTest.java

Closes #83 
Copied class to implement github authorization from artipie, added test.

feat: added github authentication

---

README.md

Part of https://github.com/artipie/artipie/issues/1031
Corrected and extended readme file.

fix: validate README.md

---

.github/workflows/update-copyright-years.yml
README.md

Part of https://github.com/artipie/artipie/issues/1031
- added telegram icon and lint to contributing guide
- added license update action

readme and license update action

---

src/main/java/com/artipie/front/Service.java

part of https://github.com/artipie/artipie/issues/1069
Added endpoint for `dashboard/{{username}}` to display dashboard user home page

fix: make dashboard/{{username}} available

---

src/main/java/com/artipie/front/auth/YamlCredentials.java
src/main/java/com/artipie/front/settings/ArtipieYaml.java
src/test/java/com/artipie/front/auth/YamlCredentialsTest.java

Part of #91 
Added `LoadingCache` to `YamlCredentials`, this will trigger to reload users every minute.

feat: reload yaml credentials

---

src/main/java/com/artipie/front/Layout.java
src/main/java/com/artipie/front/Service.java
src/main/java/com/artipie/front/rest/SettingsService.java
src/main/java/com/artipie/front/ui/repository/RepoList.java

@olenagerasimova Please review

feat: Getting layout setting on startup from rest service

---

src/main/resources/html/repository/create
src/main/resources/info/conan.info.html

Adding support for conan repository type. Part of #121

Initial conan support

---

.github/workflows/ci-checks.yml
.github/workflows/release.yml
pom.xml

Removed ppom usage and updated some deps.

do not use parent pom

---

Dockerfile

Closes https://github.com/artipie/artipie/issues/1360

fix: use java 21 in Dockerfile
